### ISSUE TITLE
Implant not found

### ISSUE THREAD

**Issue by useragent23253** [D1rkMtr/VirusTotalC2#4]
I got some warnings in vs2019, but i don't think is important. I compiled and executed implant. I got these errors

Server:
TeamServer.exe eb9f09d10dd7b3b5a0216fa5644e7270034cca2859aed4299db1af779da69a5b
Implant # getuid
[+] Task Encoded : Z2V0dWlkKipUMzRNKiox
[+] Result Encoded : (null)
(NULL)

'**1MPL4NT**' not found.[+] Result Decoded :

Client:
Implant.exe eb9f09d10dd7b3b5a0216fa5644e7270034cca2859aed4299db1af779da69a5b
task (null)
(NULL)
[+]Decoded Task :

'**T34M**' not found.
task (null)
(NULL)
[+]Decoded Task :

'**T34M**' not found.
task (null)
(NULL)

Any suggestions?
or i just need upgrade my VT account to premium?

**Comment by D1rkMtr** [comment]
Unfortunately it gets patched by VirusTotal, i just test it 😕

**Comment by D1rkMtr** [comment]
But I will unpatch it and reupload it

**Comment by D1rkMtr** [comment]
not working bcz VirusTotal Comment's POST API wich is used to drop a comment is not working for the moment , so the task and the result of executing the task is not possible to post them on VirusTotal infrastructure for the moment , we see in the future how VirusTotal will change the API and create a new C2.

**Comment by useragent23253** [comment]
Sadly. Thanks for your feedback

**Comment by D1rkMtr** [comment]
![Unpatched](https://user-images.githubusercontent.com/110354855/193456969-7517b2b9-a034-4045-878f-04ed2be751d7.png)

**Comment by D1rkMtr** [comment]
still unpatched just provide a valid API key for both implant and Team server

**Comment by useragent23253** [comment]
which line in code where i should to put my api?

**Comment by useragent23253** [comment]
sorry for stupid question, found it

**Comment by useragent23253** [comment]
working, but I've not nothing in log on Teamserver side. After 5 minutes implant stopped responding. Still thinking problem in VT api. I mean should to upgrade it to premium. Do u use premium api or not?

Server side log
Implant # cmd ipconfig
[+] Task Encoded : Y21kIGlwY29uZmlnKipUMzRNKioz
[+] Result Encoded : Y21kIGlwY29uZmlnKipUMzRNKioz

'**1MPL4NT**' not found.[+] Result Decoded :

**Comment by D1rkMtr** [comment]
This version of VirusTotalC2 doesn't support chunking big result output , ipconfig generate big output, so the solution is to chunk the output then send it, which is not supported on this version

**Comment by D1rkMtr** [comment]
I leave it for the users to do it.
